// react-app/src/components/AddCar/AddCar.js
import React from 'react'

const AddCar = props => {

    const formSubmit = (e) => {
         e.preventDefault()
        console.log(e)
    }

    // const onUpdateValue = (e) => {
    //     // console.log(e)
    //     props.updateInputValues(e.target.name, e.target.value)
    // }

    return (
        <form onSubmit={formSubmit}>
            {/*<label>Брэнд:*/}
            {/*    <input type="text"*/}
            {/*           value={props.inputSettings.value.brand}*/}
            {/*           onChange={onUpdateValue}*/}
            {/*           name={props.inputSettings.name.brand}*/}
            {/*    />*/}
            {/*</label>*/}
            <label>Модель:
                <input type="text"
                       value={props.inputSettings.value.model}
                       name={props.inputSettings.name.model}
                       // onChange={onUpdateValue}
                />
            </label>
            {/*<label>Год выпуска:*/}
            {/*    <input type="text"*/}
            {/*           value={props.inputSettings.value.year}*/}
            {/*           name={props.inputSettings.name.year}*/}
            {/*           onChange={onUpdateValue}*/}
            {/*    />*/}
            {/*</label>*/}
            {/*<label>Цена:*/}
            {/*    <input type="text"*/}
            {/*           value={props.inputSettings.value.price}*/}
            {/*           name={props.inputSettings.name.price}*/}
            {/*           onChange={onUpdateValue}*/}
            {/*    />*/}
            {/*</label>*/}
            <div>
                <button type="submit">Добавить</button>
            </div>
        </form>
    )
}

export default AddCar

// angular-app/src/app/addcar/addcar.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-addcar',
  templateUrl: './addcar.component.html',
  styleUrls: ['./addcar.component.css']
})
export class AddcarComponent implements OnInit {

  constructor(public httpClient: HttpClient) {
  }

  inputs = {
    brand: '',
    model: '',
    price: '',
    year: ''
  }

  addCar() {
    this.httpClient.post('http://localhost:8080/api/cars', this.inputs).subscribe(data => {
      console.log('success')
    }, error => {
      console.log('failed')
    })
    this.inputs.brand = ''
    this.inputs.model = ''
    this.inputs.price = ''
    this.inputs.year = ''
  }

  ngOnInit(): void {
  }

}

<form class="form">
  <label>Брэнд:
    <input [(ngModel)]="inputs.brand" type="text" name="brand"/>
  </label>
  <label>Модель:
    <input [(ngModel)]="inputs.model" type="text" name="model"/>
  </label>
  <label>Год выпуска:
    <input [(ngModel)]="inputs.year" type="number" name="year"/>
  </label>
  <label>Цена:
    <input [(ngModel)]="inputs.price" type="number" name="price"/>
  </label>
  <div class="action">
    <button (click)="addCar()" type="button">
      Добавить
    </button>
  </div>
</form>
