// react-app/src/components/About/About.js
import React from 'react'
import style from './About.module.css'
import studentPhoto from '../../assets/images/studentPhoto.jpg'

const About = props => {
    return (
        <div className={style.about}>
            <div className={style.image}>
                <img src={studentPhoto} alt="img"/>
            </div>
           <div className={style.info}>
               <p>ФИО: Шевченко Артур Максимович</p>
               <p>Группа: CKW29</p>
           </div>
        </div>
    )
}

export default About

// angular-app/src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  constructor() { }


  ngOnInit(): void {
  }

}

<div class="about">
  <div class="about__image">
    <img src='./assets/images/studentPhoto.jpg' alt="img"/>
  </div>
  <div class="about__info">
    <p>ФИО: Шевченко Артур Максимович</p>
    <p>Группа: CKW29</p>
  </div>
</div>
