// angular-app/src/app/list-car/list-car.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {CarsApiService} from "../services/cars-api.service";
import {Router} from "@angular/router";
import {NotificationService} from "../services/notification.service";

@Component({
  selector: 'app-list-car',
  templateUrl: './list-car.component.html',
  styleUrls: ['./list-car.component.css']
})

export class ListCarComponent implements OnInit {

  constructor(public httpClient: HttpClient,
              public carsApi: CarsApiService,
              public router: Router,
              public notification: NotificationService
  ) {
  }

  notificationMessage: string = 'Машина была удалена!'

  onEdit(id: number) {
    this.router.navigate(['/edit-car'])
    this.carsApi.editedCarId = id
  }

  onDelete(id: number) {
    this.carsApi.deleteCar(id)

    this.notification.setDeleteNotificationToggle(true)

    if(this.notification.notificationFlags.isDelete) {
      setTimeout(() => {
        this.notification.setDeleteNotificationToggle(false)
      }, 2000)
    }
  }

  ngOnInit(): void {
    this.carsApi.getCars()
  }
}

<table>
  <thead>
  <tr>
    <td>id</td>
    <td>Бренд</td>
    <td>Модель</td>
    <td>Цена</td>
    <td>Год Выпуска</td>
    <td></td>
    <td></td>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let car of carsApi.cars">
    <td>{{car.id}}</td>
    <td>{{car.brand}}</td>
    <td>{{car.model}}</td>
    <td>{{car.price}}</td>
    <td>{{car.year}}</td>
    <td>
      <img (click)="onEdit(car.id)" src='./assets/icons/editIcon.svg' alt="Edit" title="Edit"/>
    </td>
    <td>
      <img (click)="onDelete(car.id)"
           src='./assets/icons/deleteIcon.svg'
           alt="Delete"
           title="Delete"/>
    </td>
  </tr>
  </tbody>
</table>

<app-notification *ngIf="notification.notificationFlags.isDelete"
                  [message]="notificationMessage">
</app-notification>

// react-app/src/components/ListCar/ListCar.js
import React from 'react'
import deleteIcon from '../../assets/images/icons/deleteIcon.svg'
import editIcon from '../../assets/images/icons/editIcon.svg'
import Notification from "../Notification/Notification";
import {NavLink} from "react-router-dom";

const ListCar = props => {

    const deleteMessage = "Машина была удалена!"

    if (props.notificationFlags.isDelete) {
        setTimeout(() => {
            props.setDeleteNotificationToggle(false)
        }, 2000)
    }

    const onDeleteCar = id => {
        props.deleteCar(id)
    }

    const onEditCar = id => {
        props.setEditedCarId(id)
    }


    return (
        <>
            {
                props.notificationFlags.isDelete ? <Notification message={deleteMessage}/> : ''
            }
            <table>
                <thead>
                <tr>
                    <td>id</td>
                    <td>Brand</td>
                    <td>Model</td>
                    <td>Year</td>
                    <td>Price</td>
                    <td></td>
                    <td></td>
                </tr>
                </thead>
                <tbody>
                {
                    props.cars.map(car => {
                        return (
                            <tr key={car.id}>
                                <td>{car.id}</td>
                                <td>{car.brand}</td>
                                <td>{car.model}</td>
                                <td>{car.year}</td>
                                <td>{car.price}</td>
                                <td>
                                    <NavLink to='edit-car'>
                                    <img onClick={() => onEditCar(car.id)} src={editIcon} alt="Edit"/>
                                    </NavLink>

                                </td>
                                <td>
                                    <img onClick={() => onDeleteCar(car.id)}
                                         src={deleteIcon}
                                         alt="Delete"
                                    />
                                </td>
                            </tr>
                        )
                    })
                }
                </tbody>
            </table>
        </>
    )
}

export default ListCar
