// angular-app/src/app/listcar/listcar.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";

export interface Car {
  id: number,
  brand: string,
  model: string,
  year: number,
  price: number
}

@Component({
  selector: 'app-listcar',
  templateUrl: './listcar.component.html',
  styleUrls: ['./listcar.component.css']
})
export class ListcarComponent implements OnInit {

  constructor(public httpClient: HttpClient) {
  }

  cars: Car[] = []

  deleteCar(id: any) {
    this.httpClient.delete(`http://localhost:8080/api/cars/${id}`).subscribe(data => {
      console.log('success')
    }, error => {
      console.log('failed')
    })
    this.cars = this.cars.filter(car => car.id !== id)
  }

  ngOnInit(): void {
    this.httpClient.get<Car[]>('http://localhost:8080/api/cars').subscribe(cars => {
      this.cars = cars
      console.log(cars)
    })
  }

}

<ul class="listcar__list">
  <li *ngFor="let car of cars" class="listcar__item">
    <div class="listcar__info">
      <p><strong>{{car.brand}} {{car.model}}</strong></p>
      <p>Цена: {{car.price}}</p>
      <p>Год выпуска: {{car.year}}</p>
    </div>
    <div class="listcar__action">
      <button>
        <img src='./assets/icons/editIcon.svg' alt="Edit" title="Edit"/>
      </button>
      <button (click)="deleteCar(car.id)">
        <img src='./assets/icons/deleteIcon.svg' alt="Delete" title="Delete"/>
      </button>
    </div>
  </li>
</ul>

// react-app/src/components/ListCar/ListCar.js
import React from 'react'
import style from './ListCar.module.css'
import deleteIcon from '../../assets/images/icons/deleteIcon.svg'
import editIcon from '../../assets/images/icons/editIcon.svg'

const ListCar = props => {

    const onDeleteCar = id => {
        props.deleteCar(id)
    }

    return (
        <ul className={style.list}>
            {
                props.cars.map(car => {
                    return (
                        <li className={style.item} key={car.id}>
                            <div className={style.info}>
                                <p><strong>{car.brand} {car.model}</strong></p>
                                <p>Цена: {car.price}</p>
                                <p>Год выпуска: {car.year}</p>
                            </div>
                            <div className={style.action}>
                                <button>
                                    <img src={editIcon} alt="Edit" title="Edit"/>
                                </button>
                                <button onClick={() => onDeleteCar(car.id)}>
                                    <img src={deleteIcon} alt="Delete" title="Delete"/>
                                </button>
                            </div>
                        </li>
                    )
                })
            }
        </ul>
    )
}

export default ListCar
