// react-app/src/components/AddCar/AddCar.js
import React from 'react'
import style from './form.module.css'
import Notification from "../Notification/Notification";

const AddCar = props => {

    const addMessage = 'Машина была добавлена!'

    const formSubmit = (e) => {
        e.preventDefault()
        props.addCar()
    }

    const onUpdateValue = (e) => {
        props.updateInputValues(e.target.name, e.target.value)
    }

    if (props.notificationFlags.isAdd) {
        setTimeout(() => {
            props.setAddToggle(false)
        }, 2000)
    }
    return (
        <form onSubmit={formSubmit} className={style.form}>
            {
                props.notificationFlags.isAdd ? <Notification message={addMessage}/> : ''
            }
            <label>Брэнд:
                <input type="text"
                       value={props.inputInfo.value.brand}
                       onChange={onUpdateValue}
                       name={props.inputInfo.name.brand}
                />
            </label>
            <label>Модель:
                <input type="text"
                       value={props.inputInfo.value.model}
                       name={props.inputInfo.name.model}
                       onChange={onUpdateValue}
                />
            </label>
            <label>Год выпуска:
                <input type="number"
                       value={props.inputInfo.value.year}
                       name={props.inputInfo.name.year}
                       onChange={onUpdateValue}
                />
            </label>
            <label>Цена:
                <input type="number"
                       value={props.inputInfo.value.price}
                       name={props.inputInfo.name.price}
                       onChange={onUpdateValue}
                />
            </label>
            <div className={style.action}>
                <button type="submit">
                    Добавить
                </button>
            </div>
        </form>
    )
}

export default AddCar

// angular-app/src/app/add-car/add-car.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {FormGroup, FormControl, Validators} from "@angular/forms";
import {CarsApiService} from "../services/cars-api.service";
import {NotificationService} from "../services/notification.service";

@Component({
  selector: 'app-add-car',
  templateUrl: './add-car.component.html',
  styleUrls: ['./add-car.component.css']
})
export class AddCarComponent implements OnInit {

  constructor(public httpClient: HttpClient,
              public carsApi: CarsApiService,
              public notification: NotificationService
  ) {}

  notificationMessage: string = 'Машина была добавлена!'

  form!: FormGroup

  ngOnInit(): void {
    this.form = new FormGroup({
      brand: new FormControl('', [Validators.required]),
      model: new FormControl('', [Validators.required]),
      year: new FormControl('', [Validators.required]),
      price: new FormControl('', [Validators.required])
    })
  }

  submit() {
    this.carsApi.addCar(this.form.value)
    this.form.reset()
    this.notification.setAddNotificationToggle(true)

    if(this.notification.notificationFlags.isAdd) {
      setTimeout(() => {
        this.notification.setAddNotificationToggle(false)
      }, 2000)
    }
  }
}

<form class="form" [formGroup]="form" (ngSubmit)="submit()">
  <label>Бренд:
    <input formControlName="brand" type="text" name="addBrand"/>
  </label>
  <label>Модель:
    <input formControlName="model" type="text" name="addModel"/>
  </label>
  <label>Год выпуска:
    <input formControlName="year" type="number" name="addYear"/>
  </label>
  <label>Цена:
    <input formControlName="price" type="number" name="addPrice"/>
  </label>
  <div class="action">
    <button type="submit">
      Добавить
    </button>
  </div>
</form>

<app-notification *ngIf="notification.notificationFlags.isAdd"
                  [message]="notificationMessage">
</app-notification>
