// react-app/src/components/EditCar/EditCar.js
import React from 'react'
import style from "../AddCar/form.module.css";
import {NavLink} from "react-router-dom";
import Notification from "../Notification/Notification";

const EditCar = props => {

    const editNotificationMessage = 'Машина была изменена!'

    if (props.notificationFlags.isEdit) {
        setTimeout(() => {
            props.setEditNotificationToggle(false)
        }, 2000)
    }

    const formSubmit = (event) => {
        event.preventDefault()
        props.onEditCar()
    }

    const onUpdateValue = (event) => props.updateEditedCarInputValues(event.target.name, event.target.value)


    return (
        <>
            {
                props.notificationFlags.isEdit ? <Notification message={editNotificationMessage}/> : ''
            }
            <form onSubmit={formSubmit} className={style.form}>
                <label>Брэнд:
                    <input type="text"
                           value={props.cars.filter(car => car.id === props.editedCarId)[0].brand}
                           name={props.inputControl.brandInput.name}
                           onChange={onUpdateValue}
                    />
                </label>
                <label>Модель:
                    <input type="text"
                           value={props.cars.filter(car => car.id === props.editedCarId)[0].model}
                           name={props.inputControl.modelInput.name}
                           onChange={onUpdateValue}
                    />
                </label>
                <label>Год выпуска:
                    <input type="number"
                           value={props.cars.filter(car => car.id === props.editedCarId)[0].year}
                           name={props.inputControl.yearInput.name}
                           onChange={onUpdateValue}
                    />
                </label>
                <label>Цена:
                    <input type="number"
                           value={props.cars.filter(car => car.id === props.editedCarId)[0].price}
                           name={props.inputControl.priceInput.name}
                           onChange={onUpdateValue}
                    />
                </label>
                <div className={style.action}>
                    <NavLink to='/list-car'>
                        <button type="button">
                            Назад к списку
                        </button>
                    </NavLink>
                    <button type="submit">
                        Редактировать
                    </button>
                </div>
            </form>
        </>
    )
}

export default EditCar

// angular-app/src/app/edit-car/edit-car.component.ts
import {Component, OnInit} from '@angular/core';
import {CarsApiService} from "../services/cars-api.service";
import {FormControl, FormGroup} from "@angular/forms";
import {Router} from "@angular/router";
import {NotificationService} from "../services/notification.service";

@Component({
  selector: 'app-edit-car',
  templateUrl: './edit-car.component.html',
  styleUrls: ['./edit-car.component.css']
})

export class EditCarComponent implements OnInit {

  constructor(public carsApi: CarsApiService,
              public router: Router,
              public notification: NotificationService
  ) {
  }

  notificationMessage: string = 'Машина была обновлена!'

  form!: FormGroup

  inputValues = {
    brand: this.carsApi.cars.filter(car => car.id === this.carsApi.editedCarId)[0].brand,
    model: this.carsApi.cars.filter(car => car.id === this.carsApi.editedCarId)[0].model,
    year: this.carsApi.cars.filter(car => car.id === this.carsApi.editedCarId)[0].year,
    price: this.carsApi.cars.filter(car => car.id === this.carsApi.editedCarId)[0].price
  }

  ngOnInit(): void {
    this.form = new FormGroup({
      brand: new FormControl(this.inputValues.brand),
      model: new FormControl(this.inputValues.model),
      year: new FormControl(this.inputValues.year),
      price: new FormControl(this.inputValues.price),
    })
  }

  navigateToListCar() {
    this.router.navigate(['/list-car'])
  }

  updateCar() {
    this.carsApi.updateCar(this.carsApi.editedCarId, this.form.value)

    this.notification.setEditNotificationToggle(true)

    if (this.notification.notificationFlags.isEdit) {
      setTimeout(() => {
        this.notification.setEditNotificationToggle(false)
      }, 2000)
    }
  }
}

<form class="form" [formGroup]="form">
  <label>Бренд:
    <input formControlName="brand" type="text" name="editBrand"/>
  </label>
  <label>Модель:
    <input formControlName="model" type="text" name="editModel"/>
  </label>
  <label>Год выпуска:
    <input formControlName="year" type="number" name="editYear"/>
  </label>
  <label>Цена:
    <input formControlName="price" type="number" name="editPrice"/>
  </label>
  <div class="action">
    <button (click)="navigateToListCar()" type="button">
      Назад к списку
    </button>
    <button (click)="updateCar()" type="submit">
      Редактировать
    </button>
  </div>
</form>

<app-notification *ngIf="notification.notificationFlags.isEdit"
                  [message]="notificationMessage"
>
</app-notification>
